[package]
name = "zetax_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version = "2.0.106", features = ["extra-traits", "full"] }


[lib]
path = "src/lib.rs"
proc-macro = true
